### ISSUE TITLE
Nuget.org publishing

### ISSUE THREAD

**Issue by vba** [WebApiContrib/WebApiContrib.Formatting.Jsonp#36]
Greetings,

I would like to know if it could be possible to publish new version (without system.web references) of your jsonp formatter to nuget.org? Many thanks.

**Comment by panesofglass** [comment]
@ChrisMissal, can you get to this? I still haven't worked out all the details on build/deploy to NuGet in WebApiContrib, and it may yet be a few more weeks.

**Comment by vba** [comment]
If you wish I could propose a FAKE script to do that, but maybe you have your own, internal mechanisms for such kind of tasks.

**Comment by panesofglass** [comment]
I've got one mostly working [here](https://github.com/WebApiContrib/WebAPIContrib) that I plan to extrapolate over to the rest of the WebApiContrib projects. It's using [this project](https://github.com/panesofglass/.build) as a bootstrapper. If you would like to help, I would certainly appreciate it! See [this PR](https://github.com/WebApiContrib/WebAPIContrib/pull/119) to understand the steps I had to take, though if you are already familiar with FAKE, you could probably knock it out quickly. I think I still have some things to do on WebAPIContrib to get it working correctly, not to mention setting up AppVeyor builds.

**Comment by panesofglass** [comment]
Thanks for your help, @vba!

**Comment by puco** [comment]
Any progress on this and new version of package? Anyhow I can help?

**Comment by ChrisMissal** [comment]
I'm new to the recent paket changes and the build is failing on the build server as well as locally for me. Can somebody with more experience take a look?

**Comment by puco** [comment]
I tried to fix the build issues in #43

**Comment by vba** [comment]
It mostly looks like a dll-hell problem. The problem exists in unit tests project, unfortunately we cannot use the reference redirection in such kind of project. I'll try to downgrade the webapi version to get it works tomorrow.

**Comment by ChrisMissal** [comment]
Thanks @vba!

**Comment by vba** [comment]
Hi,

I got new elements. As I said before, and I confirm it, it's a dll hell trouble. First, I checked my pull request version to be sure that it didn't come from my modifications (it wasn't case) and then I checked current state of the project. I my case I get such kind of messages when I try to run the tests:
```bash
Test Error : WebApiContrib.Formatting.Jsonp.Tests.JsonpMediaTypeFormatterTests.CanReadType_AlwaysReturnsFalse
   System.IO.FileLoadException : Could not load file or assembly 'System.Net.Http.Formatting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at WebApiContrib.Formatting.Jsonp.Tests.JsonpMediaTypeFormatterTests.CanReadType_AlwaysReturnsFalse()
```
When I try to compare the test dll's references of my version (before merge above) and the actual version (after merge below) I see the difference:

![2015-07-30 08_54_19-telerik justdecompile - temporary list - 2 files](https://cloud.githubusercontent.com/assets/420881/8977543/5f087066-369a-11e5-846d-151e4687f292.png)

So as you can see there's a trouble. Such kind of runtime stuff is painful, I could try to find time to fix it, but I couldn't be sure to be available this week.

**Comment by vba** [comment]
Described patch works for me. Could anybody try it and feedback me please?

```patch
From 70bd4199f6749dc74920b224ea2c25c62dde8376 Mon Sep 17 00:00:00 2001
From: Victor Bartel <victor.bartel@dgtresor.gouv.fr>
Date: Fri, 7 Aug 2015 16:11:21 +0200
Subject: [PATCH] [Fix] Fixing dll-hell after careless merge

---
 .../WebApiContrib.Formatting.Jsonp.csproj                         | 8 ++++----
 .../WebApiContrib.Formatting.Jsonp.Tests.csproj                   | 8 --------
 2 files changed, 4 insertions(+), 12 deletions(-)

diff --git a/src/WebApiContrib.Formatting.Jsonp/WebApiContrib.Formatting.Jsonp.csproj b/src/WebApiContrib.Formatting.Jsonp/WebApiContrib.Formatting.Jsonp.csproj
index cc2267b..d7c0756 100644
--- a/src/WebApiContrib.Formatting.Jsonp/WebApiContrib.Formatting.Jsonp.csproj
+++ b/src/WebApiContrib.Formatting.Jsonp/WebApiContrib.Formatting.Jsonp.csproj
@@ -37,13 +37,13 @@
     <Reference Include="System" />
     <Reference Include="System.Core" />
     <Reference Include="System.Net.Http" />
-    <Reference Include="System.Net.Http.Formatting, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
+    <Reference Include="System.Net.Http.Formatting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
       <SpecificVersion>False</SpecificVersion>
-      <HintPath>..\..\packages\Microsoft.AspNet.WebApi.Client.5.0.0\lib\net45\System.Net.Http.Formatting.dll</HintPath>
+      <HintPath>..\..\packages\Microsoft.AspNet.WebApi.Client\lib\net45\System.Net.Http.Formatting.dll</HintPath>
     </Reference>
-    <Reference Include="System.Web.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
+    <Reference Include="System.Web.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
       <SpecificVersion>False</SpecificVersion>
-      <HintPath>..\..\packages\Microsoft.AspNet.WebApi.Core.5.0.0\lib\net45\System.Web.Http.dll</HintPath>
+      <HintPath>..\..\packages\Microsoft.AspNet.WebApi.Core\lib\net45\System.Web.Http.dll</HintPath>
     </Reference>
   </ItemGroup>
   <ItemGroup>
diff --git a/test/WebApiContrib.Formatting.Jsonp.Tests/WebApiContrib.Formatting.Jsonp.Tests.csproj b/test/WebApiContrib.Formatting.Jsonp.Tests/WebApiContrib.Formatting.Jsonp.Tests.csproj
index 4dc6625..afe431a 100644
--- a/test/WebApiContrib.Formatting.Jsonp.Tests/WebApiContrib.Formatting.Jsonp.Tests.csproj
+++ b/test/WebApiContrib.Formatting.Jsonp.Tests/WebApiContrib.Formatting.Jsonp.Tests.csproj
@@ -37,14 +37,6 @@
     <Reference Include="System" />
     <Reference Include="System.Core" />
     <Reference Include="System.Net.Http" />
-    <Reference Include="System.Net.Http.Formatting, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
-      <SpecificVersion>False</SpecificVersion>
-      <HintPath>..\..\packages\Microsoft.AspNet.WebApi.Client\lib\net45\System.Net.Http.Formatting.dll</HintPath>
-    </Reference>
-    <Reference Include="System.Web.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
-      <SpecificVersion>False</SpecificVersion>
-      <HintPath>..\..\packages\Microsoft.AspNet.WebApi.Core\lib\net45\System.Web.Http.dll</HintPath>
-    </Reference>
     <Reference Include="System.Net.Http.WebRequest" />
     <Reference Include="System.Xml.Linq" />
     <Reference Include="System.Data.DataSetExtensions" />
-- 
1.9.4.msysgit.0
```

**Comment by ChrisMissal** [comment]
Nice @vba! I'll get this added, committed, merged, and hopefully a new NuGet deployed momentarily.

**Comment by ChrisMissal** [comment]
Version 3.0.1 has been published: https://www.nuget.org/packages/WebApiContrib.Formatting.Jsonp/

/cc @vba @panesofglass @puco
