### ISSUE TITLE
Prevent "Rosetta Flash JSONP abuse"

### ISSUE THREAD

**Issue by JProgrammer** [WebApiContrib/WebApiContrib.Formatting.Jsonp#38]
When looking through the code it does not appear to apply a fix for the "Rosetta Flash JSONP abuse"
Issue see: https://miki.it/blog/2014/7/8/abusing-jsonp-with-rosetta-flash/

expressjs from the node community formats jsonp like this:

	    // the /**/ is a specific security mitigation for "Rosetta Flash JSONP abuse"
	    // the typeof check is just to reduce client error noise
	    body = '/**/ typeof ' + callback + ' === \'function\' && ' + callback + '(' + body + ');';

**Comment by panesofglass** [comment]
I was unaware of the vulnerability. Thank you for pointing it out!

**Comment by panesofglass** [comment]
@JProgrammer has this been resolved?

**Comment by JProgrammer** [comment]
Yes commit looks good
