### ISSUE TITLE
Reflected XSS on callback parameter

### ISSUE THREAD

**Issue by puco** [WebApiContrib/WebApiContrib.Formatting.Jsonp#40]
The JSONP callback parameter should be validated and the formatter should return a 500 and not render the callback parameter to the response.

**Comment by panesofglass** [comment]
A PR would be appreciated. I don't use this formatter anymore and don't have the time to investigate at present. Thanks!

**Comment by puco** [comment]
I didn't have time for it yesterday but will try to do it today.

**Comment by puco** [comment]
It is not entirely perfect, there are possible callback parameters that are valid javascript (noone says you can't have a obj.inst['lookup'].on[other] callback, which would not result in broken code. So far it allows basic functions names and functions defined within objects. I also fixed tests for the roseta bug.
