### ISSUE TITLE
3.0.1 NuGet Package Overwrites WebApi 2 Assemblies

### ISSUE THREAD

**Issue by afyles** [WebApiContrib/WebApiContrib.Formatting.Jsonp#45]
Despite the nuspec which shows a dependency of WebApi.Core > 5.0.0, the package downgrades WebApi.Core 5.2.3 to 5.0.0 which in shipped in the package.  This is a bit confusing as once you install the package you are unable to build a WebApi 2 project.

**Comment by michaelshane** [comment]
Anyone solve this? Having the same issue.

**Comment by panesofglass** [comment]
PRs are welcome. I don't know why NuGet would ignore the dependency version. Which version of the NuGet client do you use?

**Comment by michaelshane** [comment]
Version 2.8. I'm not familiar with how nuget packages are compiled, but in paket.depencies should 

    8: nuget Microsoft.AspNet.WebApi.Core 5.0.0

be 

    8: nuget Microsoft.AspNet.WebApi.Core >= 5.0.0

and likewise 

    18: nuget Newtonsoft.Json 5.0.8

be 

    18: nuget Newtonsoft.Json >= 5.0.8


or something like that?

**Comment by elryry** [comment]
I am also experiencing this issue. After installing WebApiContrib.Formatting.Jsonp package the WebAPI project references is changed to be 5.0.0, however NuGet still displays 5.2.3 being the installed version.

**Comment by panesofglass** [comment]
Whoa, I didn't realize this one had bumped up to paket. @michaelshane, yes, those should have `>=`, I think.

**Comment by anovinska** [comment]
I am also experiencing this issue.

**Comment by nickheppleston** [comment]
*Me too*, however I did fix it with some NuGet gymnastics - I will try and remember what I did.

**Comment by panesofglass** [comment]
Looking more closely, I don't see an issue in the NuGet package. It shows the only dependency is Microsoft.AspNet.WebApi.Core >= 5.0.0. However, I see that the package also includes several Web API assemblies. I'll add a paket.template to fix this.

**Comment by panesofglass** [comment]
This _should_ be fixed by commit c6960d5bff225eb4c2211286fcb790072deb4f32.

**Comment by panesofglass** [comment]
@ChrisMissal, can you publish?

**Comment by panesofglass** [comment]
Fixed and published: https://www.nuget.org/packages/WebApiContrib.Formatting.Jsonp
