### ISSUE TITLE
Using Attribute Routing with WebApiContrib.Formatting.Jsonp

### ISSUE THREAD

**Issue by nickheppleston** [WebApiContrib/WebApiContrib.Formatting.Jsonp#47]
I have an existing Web API solution that needs to support JSONP as a new backwards-compat feature.

We currently use Attribute Routing using the following line in my WebApiConfig class:

```
config.MapHttpAttributeRoutes();
```

We have a single Controller with multiple methods that look like this:

```
[Route("address-search/streetname/{streetName}")]
[HttpGet]
public HttpResponseMessage AddressSearchByStreetName(string streetName)
```

and

```
[Route("address-search/postcode/{postCode}")]
[HttpGet]
public HttpResponseMessage AddressSearchByPostCode(string postCode)
```

However, we do not receive JSONP callback formatting in the JSON response.

If however, I create a new controller as follows: 

```
public class JsonpController : ApiController
{
    [HttpGet]
    public string Get(int id)
    {
        return (String.Format("JSONP passed: {0}", id));
    }
}
```

and define the following route in my WebApiConfig class:

```
config.Routes.MapHttpRoute(
    name: "DefaultApi",
    routeTemplate: "{controller}/{id}",
    defaults: new { id = RouteParameter.Optional }
);
```

I get the required response using the url _http://localhost:50596/jsonp/101?callback=jsonpcallback_ with an _Accept: text/javascript_ header:

```
/**/ typeof jsonpcallback === 'function' && jsonpcallback("JSONP passed: 101");
```

**So, $64k question - how can I get WebApiContrib.Formatting.Jsonp working with Attribute Routing?**

**Comment by panesofglass** [comment]
The [sample app](https://github.com/WebApiContrib/WebApiContrib.Formatting.Jsonp/blob/master/samples/WebApiContrib.Formatting.Jsonp.SampleWebHost/Global.asax.cs#L19) demonstrates this very thing. I wonder what the differences in the sample might be from your own app.

**Comment by nickheppleston** [comment]
After much head-scratching, it turns out that the return type from my controller method was at fault.

I was using a return type of **HttpResponseMessage**, however it would appear that if I use a Value Type (or types that 'behave' like value types) e.g. int, string etc. -or- IHttpActionResult as the Controller Method return type, everything works as expected.

**Comment by panesofglass** [comment]
I'm happy you were able to resolve it!
